### ISSUE TITLE
Navbar on mobile places items outside of it and stretches logo

### ISSUE THREAD

**Issue by cam-perry** [QTMA-teamb/Chyp#20]
![](https://i.imgur.com/Y5ckwl8.jpg)

**Comment by cam-perry** [comment]
![](https://i.imgur.com/2l9R3Ia.jpg)

Seems to have corrected. Or did you deploy something that quickly?

**Comment by cam-perry** [comment]
![](https://i.imgur.com/7JXS7m6.jpg)

**Comment by katieyang** [comment]
I'll take this one :) Hamburger!

**Comment by katieyang** [comment]
Pushed fix.
